### ISSUE TITLE
Mögliche Domains für neues Portal

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/coding-board-community#3]
In https://github.com/dominikbraun/coding-board-community/issues/2 wurden bereits einige Möglichkeiten für die Domain eines potenziellen neuen Portals genannt.

### Bisherige TLDs:
* .de
* .net
* .dev
* .forum (ab 2020, genauer Einführungszeitpunkt unbekannt)

### Bisherige Domainnamen:
* dev-community.de
* entwickler-board.de
* developer-board.de
* coding-community.dev
* coder-board.net

**Weitere Domainnamen sowie eure Präferenzen könnt ihr hier gerne ergänzen!**

**Comment by dominikbraun** [comment]
Ich persönlich würde ich eine `.de`- oder eine `.dev`-TLD am besten finden, aber je nach Hostnamen gibt es sicherlich auch andere gute Kombinationen. `.io` gäb's auch noch.

**Comment by asccc** [comment]
.io kostet bei Namecheap 5 mal mehr als eine .de Domain 😁 
.dev oder .de fände ich ebenfalls am idealsten.

Bei .de ist wohl direkt klar um welche Sprache es sich handelt, .dev hingegen ist "cooler" 😃 

Mir fällt als mögliches Wort für eine zusammengesetzte Domain noch "union" ein. 
Das ist zweideutig für "Gemeinschaft/Zusammenschluss" und hat Bezug zum coden (C/C++).

**Comment by german-one** [comment]
Ist kein Geheimnis, dass man naturgemäß eher auf englischsprachigen Seiten surft wenn man sich mit Softwareentwicklung beschäftigt. Mein einfallsloser Nickname rührt auch daher, dass ich mich in der Vergangenheit mehr in solchen Communities bewegt habe. Gegen Seiten wie SO kann eine deutschsprachige Community auch nicht anstinken. Sie würde nie diese Größe und Bedeutung erlangen. Aber es war so etwas wie ein Alleinstellungsmerkmal des CB, dass es die beste (mir bekannte) deutsche Seite auf diesem Gebiet war. Wenn die neue Seite deutschsprachig bleiben soll, wäre ein `.de` vermutlich am sinnvollsten (andererseits genauso einfallslos wie mein Nick 😛).

**Comment by BAGZZlash** [comment]
Ich sehe das wie @german-one (diesmal richtig?), wir können nur den "deutschen Markt" bedienen. Daher bin ich auch für .de. Eigentlich gefällt mir "coding-community" gut, aber man könnte den o.g. Gedanken ja noch etwas fortführen und auch den Domainnamen deutsch halten, z.B. mittels "entwickler-board". Andererseits klingt diese Mixtur aus Deutsch und Englisch wieder etwas holprig, und die Sprache des Programmierens ist nun mal Englisch, da klingt jeder deutsche Begriff irgendwie gekünstelt.

Fazit: "coding-community.de" wäre mein Favorit. Hm, aber [da ist ja schon was](http://coding-community.de/).

**Comment by alinnert** [comment]
Sind wir auf solche allgemeinen Begriffe festgenagelt? Ich mag es ja, wenn man aus einem allgemein bekannten Phänomen oder Konstrukt einen Namen macht. So wie eben StackOverflow. Was da vllt. noch zu klären wäre ist die Zielgruppe der Community. Soll sich das an die Allgemeinheit richten oder speziell an Anfänger? (Ich hab halt in der Zeit, in der ich im CB aktiv war, mitbekommen, dass wohl viele Neulinge davon angezogen wurden.) Das könnte man ggf. auch im Domain-Namen widerspiegeln.

**Ein paar Ideen:**

codetime.de (als Anspielung auf runtime; Alternativen mit Suffix -board, -forum etc.)
void-main.de
hello-board.de (von "hello world")
null-board.de
null-point.de (&larr; das mag ich tatsächlich sogar.)

Um solche Domains leichter auffindbar zu machen, kann man so etwas wie "Entwickler-Community" ja als Untertitel verwenden.

**Comment by dominikbraun** [comment]
Ja, über einen Eigennamen oder eine Anspielung eines fachlichen Begriffes hab ich auch schon nachgedacht.

Damit hätte man einige Vorteile: Der Spagat zwischen deutschen und englischen Wörtern fällt weg, bei der Verfügbarkeit der Domain hat man bessere Chancen und der Wiedererkennungswert ist wohl auch größer.

Aber welcher Begriff ist so geläufig, dass ihn auch die von @alinnert genannten Neulinge peilen? :thinking:

**Comment by dominikbraun** [comment]
Es ist unglaublich: Selbst Sachen wie [while-true.de](http://while-true.de/) sind vergeben :rofl:

**Comment by alinnert** [comment]
~~~ c
while (true) {
  print("Hier entsteht etwas Neues! :)");
}
~~~

:D

**Comment by IngressoDev** [comment]
BufferUnderflow.de (Ich denke keine Erklärung notwendig)

**Comment by BAGZZlash** [comment]
Ich fand void-main.de richtig gut. Leider weg.
bufferunderflow.de ist unglaublicherweise noch frei.

**Comment by dominikbraun** [comment]
Da haben wir jetzt natürlich die Büchse der Pandora geöffnet. Allerdings sollten wir auch bei den allgemeingültigeren Namen weiterhin die Augen offenhalten, beispielsweise gefällt mir der Vorschlag von @ascccc mit `union` im Namen auch ganz gut.

**Comment by jr-cologne** [comment]
Nicht schlecht. Ihr habt ja richtig kreative Ideen für eine Domain! :open_mouth: :+1:

**Comment by jr-cologne** [comment]
> Soll sich das an die Allgemeinheit richten oder speziell an Anfänger? (Ich hab halt in der Zeit, in der ich im CB aktiv war, mitbekommen, dass wohl viele Neulinge davon angezogen wurden.)

Neulinge sind innerhalb eines gewissen Maßes nicht schlecht, da diese meist für mehr Aktivität sorgen.
Im Grunde soll sich das neue Forum aber an die Allgemeinheit richten und vor allem auch einen Austausch auf höherem Niveau zwischen Gleichgesinnten erlauben.
Deswegen ja gerade auch kein einfaches Q&A-Portal.

**Comment by dominikbraun** [comment]
`codeunion.de` gäb's noch.

**Comment by jr-cologne** [comment]
So, mir erscheint, dass hier nicht mehr allzu viele Vorschläge folgen werden.
Ich würde daher vorschlagen, dass wir über die Weihnachtstage schon mal eine Abstimmung starten, welche Domain es denn werden soll.
Hierzu werde ich heute im Laufe des Tages ein weiteres Issue öffnen, in dem ihr dann per Upvoting (mit der Reaction Daumen hoch) eines Beitrages für eine Domain stimmen könnt.
Im besten Fall sucht ihr euch natürlich ein, zwei Favoriten aus und votet nicht für alle Domains, die euch irgendwo gefallen. :grinning:

**Comment by jr-cologne** [comment]
Da die Entscheidung in #4 auf dev-community.de gefallen ist, hat sich das Thema hier erledigt.
