### ISSUE TITLE
Abstimmung über die Domain für das neue Portal

### ISSUE THREAD

**Issue by jr-cologne** [dominikbraun/coding-board-community#4]
Hallo zusammen,
hier könnt ihr für eure favorisierten Domains für unser neues Portal abstimmen.

Gewertet wird die Anzahl an "Daumen hoch"-Reaktionen auf einen Beitrag mit der entsprechenden Domain.

Vielen Dank im Voraus für eure Beteiligung am Abstimmungsverfahren. 😃

**Comment by jr-cologne** [comment]
dev-community.de

**Comment by jr-cologne** [comment]
entwickler-board.de

**Comment by jr-cologne** [comment]
developer-board.de

**Comment by jr-cologne** [comment]
coding-community.dev

**Comment by jr-cologne** [comment]
coder-board.net

**Comment by jr-cologne** [comment]
codetime.de

**Comment by jr-cologne** [comment]
hello-board.de

**Comment by jr-cologne** [comment]
null-board.de

**Comment by jr-cologne** [comment]
null-point.de

**Comment by jr-cologne** [comment]
BufferUnderflow.de

**Comment by jr-cologne** [comment]
codeunion.de

**Comment by jr-cologne** [comment]
coder-community.de

**Comment by jr-cologne** [comment]
thecodingcommunity.de

**Comment by jr-cologne** [comment]
coder-forum.de

**Comment by dominikbraun** [comment]
Alternativ zum vergebenen void-main.de: function-main.de

**Comment by asccc** [comment]
void main ist halt DER Anfängerfehler in C/C++

Mir würde es jedes mal kalt den Rücken runterlaufen wenn ich diese Domain regelmäßig öffnen müsste haha

**Comment by dominikbraun** [comment]
Beim bisherigen Favoriten dev-community.de dürfte die SEO ganz interessant werden:

![image](https://user-images.githubusercontent.com/36575275/71406838-9f8c8800-2639-11ea-81f4-f6f51e6a7698.png)

**Comment by jr-cologne** [comment]
Die Weihnachtstage sind vorbei, hoffentlich habt ihr sie alle erfolgreich und gut überstanden. :snowman_with_snow: 

Aktuell ist die Domain dev-community.de eindeutig mit 6 Stimmen auf dem ersten Platz.
Wenn jemand noch nicht abgestimmt hat, hat derjenige noch bis morgen Abend um ca. 20 Uhr Zeit. Danach werde ich hier kurz das Ergebnis verkünden und mir im Anschluss die jeweilige Domain sichern.

**Comment by dominikbraun** [comment]
@jast, @Sven-Moennich und @alinnert haben glaube ich noch nicht abgestimmt.

**Comment by Sven-Moennich** [comment]
Mir ist das relativ egal. dev-community find ich ok

**Comment by jr-cologne** [comment]
Gut, ich würde sagen, wir beenden die Abstimmung hiermit. @jast und @alinnert könnten ohnehin nicht mehr viel am Ergebnis ändern.

Ich werde mir jetzt die Domain dev-community.de sichern und dann schauen wir die Tage, wie es weiter geht.
